INSERT INTO brand (id, label) VALUES (1, 'Aston Martin Lagonda Ltd');
INSERT INTO brand (id, label) VALUES (2, 'Audi');
INSERT INTO brand (id, label) VALUES (3, 'BMW');
INSERT INTO brand (id, label) VALUES (4, 'Bugatti');
INSERT INTO brand (id, label) VALUES (5, 'Chevrolet');
INSERT INTO brand (id, label) VALUES (6, 'Ferrari North America. Inc.');
INSERT INTO brand (id, label) VALUES (7, 'Jaguar');
INSERT INTO brand (id, label) VALUES (8, 'Lamborghini');
INSERT INTO brand (id, label) VALUES (9, 'MASERATI');
INSERT INTO brand (id, label) VALUES (10, 'MAZDA');
INSERT INTO brand (id, label) VALUES (11, 'NISSAN');
INSERT INTO brand (id, label) VALUES (12, 'Porsche');
INSERT INTO brand (id, label) VALUES (13, 'TOYOTA');
INSERT INTO brand (id, label) VALUES (14, 'Bentley');
INSERT INTO brand (id, label) VALUES (15, 'LEXUS');
INSERT INTO brand (id, label) VALUES (16, 'Mercedes-Benz');
INSERT INTO brand (id, label) VALUES (17, 'Mini');
INSERT INTO brand (id, label) VALUES (18, 'Subaru');
INSERT INTO brand (id, label) VALUES (19, 'Ford');
INSERT INTO brand (id, label) VALUES (20, 'Acura');
INSERT INTO brand (id, label) VALUES (21, 'Cadillac');
INSERT INTO brand (id, label) VALUES (22, 'GENESIS');
INSERT INTO brand (id, label) VALUES (23, 'KIA');
INSERT INTO brand (id, label) VALUES (24, 'Mitsubishi Motors Corporation');
INSERT INTO brand (id, label) VALUES (25, 'Volkswagen');
INSERT INTO brand (id, label) VALUES (26, 'Volvo Cars of North America. LLC');
INSERT INTO brand (id, label) VALUES (27, 'ALFA ROMEO');
INSERT INTO brand (id, label) VALUES (28, 'Dodge');
INSERT INTO brand (id, label) VALUES (29, 'Honda');
INSERT INTO brand (id, label) VALUES (30, 'HYUNDAI MOTOR COMPANY');
INSERT INTO brand (id, label) VALUES (31, 'INFINITI');
INSERT INTO brand (id, label) VALUES (32, 'Chrysler');
INSERT INTO brand (id, label) VALUES (33, 'Rolls-Royce Motor Cars Limited');
INSERT INTO brand (id, label) VALUES (34, 'GMC');
INSERT INTO brand (id, label) VALUES (35, 'RAM');
INSERT INTO brand (id, label) VALUES (36, 'Jeep');
INSERT INTO brand (id, label) VALUES (37, 'Buick');
INSERT INTO brand (id, label) VALUES (38, 'Lincoln');
INSERT INTO brand (id, label) VALUES (39, 'MITSUBISHI MOTORS');
INSERT INTO brand (id, label) VALUES (40, 'FIAT');
INSERT INTO brand (id, label) VALUES (41, 'Land Rover');
