INSERT INTO car_type (id, label) VALUES (1, 'Two Seaters');
INSERT INTO car_type (id, label) VALUES (2, 'Minicompact Cars');
INSERT INTO car_type (id, label) VALUES (3, 'Subcompact Cars');
INSERT INTO car_type (id, label) VALUES (4, 'Compact Cars');
INSERT INTO car_type (id, label) VALUES (5, 'Midsize Cars');
INSERT INTO car_type (id, label) VALUES (6, 'Large Cars');
INSERT INTO car_type (id, label) VALUES (7, 'Small Station Wagons');
INSERT INTO car_type (id, label) VALUES (8, 'Midsize Station Wagons');
INSERT INTO car_type (id, label) VALUES (9, 'Small Pick-up Trucks 2WD');
INSERT INTO car_type (id, label) VALUES (10, 'Small Pick-up Trucks 4WD');
INSERT INTO car_type (id, label) VALUES (11, 'Standard Pick-up Trucks 2WD');
INSERT INTO car_type (id, label) VALUES (12, 'Standard Pick-up Trucks 4WD');
INSERT INTO car_type (id, label) VALUES (13, 'Special Purpose Vehicle 2WD');
INSERT INTO car_type (id, label) VALUES (14, 'Special Purpose Vehicle 4WD');
INSERT INTO car_type (id, label) VALUES (15, 'Special Purpose Vehicle cab chassis');
INSERT INTO car_type (id, label) VALUES (16, 'Special Purpose Vehicle. minivan 2WD');
INSERT INTO car_type (id, label) VALUES (17, 'Special Purpose Vehicle. minivan 4WD');
INSERT INTO car_type (id, label) VALUES (18, 'Small SUV 2WD');
INSERT INTO car_type (id, label) VALUES (19, 'Small SUV 4WD');
INSERT INTO car_type (id, label) VALUES (20, 'Standard SUV 2WD');
INSERT INTO car_type (id, label) VALUES (21, 'Standard SUV 4WD');
